export const demoRooms = [
  {
    _id: "demo-1",
    title: "Sunlit studio near North Campus",
    city: "Delhi",
    area: "Kamla Nagar",
    rent: 12500,
    type: ["Room"],
    facilities: ["Wi-Fi", "AC", "Power backup"],
    images: [{ url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=86" }],
    owner: { name: "Aarav Mehta" },
    rating: 4.8,
  },
  {
    _id: "demo-2",
    title: "Cozy girls PG with meals",
    city: "Gurugram",
    area: "Sector 43",
    rent: 9800,
    type: ["PG"],
    facilities: ["Meals", "Wi-Fi", "Laundry"],
    images: [{ url: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1200&q=86" }],
    owner: { name: "Nisha Homes" },
    rating: 4.6,
  },
  {
    _id: "demo-3",
    title: "Modern room close to metro",
    city: "Noida",
    area: "Sector 62",
    rent: 14500,
    type: ["Room"],
    facilities: ["Attached bath", "AC", "Parking"],
    images: [{ url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=86" }],
    owner: { name: "Rohit Singh" },
    rating: 4.9,
  },
  {
    _id: "demo-4",
    title: "Greenview coliving for students",
    city: "Bengaluru",
    area: "Koramangala",
    rent: 16000,
    type: ["PG"],
    facilities: ["Gym", "Meals", "Housekeeping"],
    images: [{ url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=86" }],
    owner: { name: "Greenview Living" },
    rating: 4.7,
  },
  {
    _id: "demo-5",
    title: "Quiet furnished room",
    city: "Pune",
    area: "Viman Nagar",
    rent: 11000,
    type: ["Room"],
    facilities: ["Furnished", "Wi-Fi", "Kitchen"],
    images: [{ url: "https://images.unsplash.com/photo-1617104678098-de229db51175?auto=format&fit=crop&w=1200&q=86" }],
    owner: { name: "Neha Kulkarni" },
    rating: 4.5,
  },
  {
    _id: "demo-6",
    title: "Premium boys PG near Cyber Hub",
    city: "Gurugram",
    area: "DLF Phase 3",
    rent: 13500,
    type: ["PG"],
    facilities: ["Meals", "AC", "Security"],
    images: [{ url: "https://images.unsplash.com/photo-1615874694520-474822394e73?auto=format&fit=crop&w=1200&q=86" }],
    owner: { name: "Urban Stay" },
    rating: 4.8,
  },
];
